### ISSUE TITLE
Slow activation time

### ISSUE THREAD

**Issue by dvcrn** [oakmac/atom-parinfer#30] opened 2015-12-08 09:27 UTC
I noticed that Parinfer is very slow with loading and currently peaks at 2s for me. 

![screen shot 2015-12-08 at 6 27 00 pm](https://cloud.githubusercontent.com/assets/688326/11652144/5e05822a-9dd9-11e5-868d-419da152b1f5.png)

Is there something I can do to speed this up?

**Comment by oakmac** [comment] 2015-12-09 03:51
Answer 1) It is difficult to diagnose this sort of thing without detailed metrics.

Answer 2) This is probably caused by Parinfer running [Paren Mode first] on all files that are loaded when Atom starts. This is a [necessary initial step] so that Indent Mode doesn't clobber your code.

Do you notice a slow launch time when Atom loads with no Lisp files initially?

Regardless of cause - I agree this is not a great User Experience and Parinfer shouldn't add significant load time to Atom. Not sure what the solution would look like off the top of my head. Maybe do the initial Paren Mode run when an editor tab receives it's first focus event?

[Paren Mode first]:https://github.com/oakmac/atom-parinfer/blob/f6cf431c635a2b3ea2f540f7c58b0b632d75bfb7/src-cljs/atom_parinfer/core.cljs#L308-L314
[necessary initial step]:https://shaunlebron.github.io/parinfer/#fixing-existing-files

**Comment by oakmac** [comment] 2015-12-23 19:53
I just released v1.0.0 with @shaunlebron's significantly [faster version](https://github.com/shaunlebron/parinfer/issues/66) of Parinfer.

Can you check and see if this helps reduce your startup time?

**Comment by oakmac** [comment] 2016-01-07 02:21
I'm going to assume this is fixed with the recent speed improvements to Parinfer.

**Closed by oakmac** 2016-01-07 02:21 UTC
